services:
  # Dashboard Web Service
  - type: web
    name: metrics-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.dashboard:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 