[theme]
primaryColor = "#007bff"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[server]
runOnSave = true
headless = true
maxUploadSize = 5
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false

[global]
developmentMode = false 